"""Loading the TSV challenge files.

Every file is read with ``pd.read_csv(path, sep="\\t")`` as required by the
challenge specification.  IDs are read as strings so identifiers such as
``"007"`` survive round-tripping, and no assumption is made about the number of
rows in any file.

Dataset location
----------------
The repository ships the real Amazon ML Challenge files **and** a small synthetic
fixture used by the test suite.  They are not interchangeable -- the fixture has
1,500 Source 1 rows and 0.4 MB in total, the real data has 2,206,821 Source 1
rows and 2.7 GB.  :func:`resolve_dataset_root` auto-detects which one is present
and always prefers the real data, so a stale ``dataset/train`` path can never
silently train a model on the fixture.

Memory
------
The real data does not fit in RAM on a typical machine (Source 2 alone is
5,034,616 rows / 467 MB of text).  Use :func:`read_tsv_chunks` or
:meth:`RawDataset.iter_chunks` for anything that scans a whole file;
:func:`read_tsv` is kept for small tables and the test fixture.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterator

import numpy as np
import pandas as pd

from ..config import (
    ADDRESS_COLUMN,
    COUNTRY_COLUMN,
    ID_COLUMN,
    NAME_COLUMN,
    SOURCE1,
    SOURCE2,
    SOURCE3,
)

LOGGER = logging.getLogger(__name__)

#: Repository root, two levels above this file.
PROJECT_ROOT = Path(__file__).resolve().parents[2]

#: Columns the pipeline operates on, in canonical order.
CANONICAL_COLUMNS: tuple[str, ...] = (ID_COLUMN, NAME_COLUMN, ADDRESS_COLUMN, COUNTRY_COLUMN)

#: Candidate dataset roots, most-preferred first.  The real challenge data lives
#: under ``dataset/student_resource/dataset``; ``dataset`` itself holds the
#: synthetic fixture generated by ``tests/make_fixture.py``.
DATASET_ROOTS: tuple[Path, ...] = (
    PROJECT_ROOT / "dataset" / "student_resource" / "dataset",
    PROJECT_ROOT / "dataset",
)

#: Row count above which :func:`read_tsv` warns before materialising a frame.
LARGE_FILE_ROWS = 1_000_000

#: Default rows per chunk for streaming reads.
DEFAULT_CHUNK_ROWS = 300_000

#: Values treated as missing in the input files.
NA_VALUES: tuple[str, ...] = ("", "NA", "N/A", "null", "NULL", "nan", "NaN")

#: Entity ids in this data set are ``S<source>-<digits>``; derived from the
#: files, not assumed, and only used for diagnostics.
ID_PATTERN = re.compile(r"^(?P<source>S[123])-(?P<number>\d+)$")

#: Column aliases tolerated in the input files, mapped to the canonical name.
COLUMN_ALIASES: dict[str, str] = {
    "id": ID_COLUMN,
    "entityid": ID_COLUMN,
    "entity_id": ID_COLUMN,
    "businessid": ID_COLUMN,
    "business_id": ID_COLUMN,
    "name": NAME_COLUMN,
    "businessname": NAME_COLUMN,
    "business_name": NAME_COLUMN,
    "company_name": NAME_COLUMN,
    "companyname": NAME_COLUMN,
    "address": ADDRESS_COLUMN,
    "businessaddress": ADDRESS_COLUMN,
    "business_address": ADDRESS_COLUMN,
    "addr": ADDRESS_COLUMN,
    "country_code": COUNTRY_COLUMN,
    "countrycode": COUNTRY_COLUMN,
    "country": COUNTRY_COLUMN,
    "nation": COUNTRY_COLUMN,
}

GT_ID_ALIASES: dict[str, str] = {
    "source1_entity_id": "source1_id",
    "s1_id": "source1_id",
    "source_1_id": "source1_id",
    "entity_id": "source1_id",
    "source1": "source1_id",
    "matched_entity_ids": "matched_ids",
    "matched_ids": "matched_ids",
    "matched_entity_id": "matched_ids",
    "match_ids": "matched_ids",
    "matches": "matched_ids",
    "s2_s3_ids": "matched_ids",
    "s2_s3_id": "matched_ids",
}

SOURCES: tuple[str, ...] = (SOURCE1, SOURCE2, SOURCE3)


# --------------------------------------------------------------------------
# dataset root resolution
# --------------------------------------------------------------------------
def _has_split(root: Path, split: str) -> bool:
    directory = root / split
    if not directory.is_dir():
        return False
    return all((directory / f"{split}_{source}.tsv").exists() for source in SOURCES)


def resolve_dataset_root(prefer: str | Path | None = None) -> Path:
    """Return the directory that holds the real ``train/`` and ``test/`` data.

    ``prefer`` short-circuits detection and is validated.  Otherwise the
    candidates in :data:`DATASET_ROOTS` are probed in order and the first one
    containing both splits wins, so the real data is preferred over the fixture.
    """
    if prefer is not None:
        candidate = Path(prefer)
        if not _has_split(candidate, "train") and not _has_split(candidate, "test"):
            raise FileNotFoundError(
                f"No train/ or test/ source files under {candidate}. Expected e.g. "
                f"{candidate / 'train' / 'train_source1.tsv'}"
            )
        return candidate
    for root in DATASET_ROOTS:
        if _has_split(root, "train") and _has_split(root, "test"):
            return root
    probed = "\n  ".join(str(r) for r in DATASET_ROOTS)
    raise FileNotFoundError(
        "Could not locate the dataset. Probed:\n  " + probed + "\n"
        "Expected layout:\n"
        "  <root>/train/{train_source1,train_source2,train_source3,train_ground_truth}.tsv\n"
        "  <root>/test/{test_source1,test_source2,test_source3}.tsv"
    )


@lru_cache(maxsize=1)
def dataset_root() -> Path:
    """Auto-detected dataset root (cached)."""
    root = resolve_dataset_root()
    LOGGER.debug("Resolved dataset root: %s", root)
    return root


def default_train_dir() -> str:
    return str(dataset_root() / "train")


def default_test_dir() -> str:
    return str(dataset_root() / "test")


# --------------------------------------------------------------------------
# reading
# --------------------------------------------------------------------------
def _normalise_columns(df: pd.DataFrame) -> pd.DataFrame:
    df = df.rename(columns=lambda c: COLUMN_ALIASES.get(str(c).strip().lower(), str(c).strip()))
    if ID_COLUMN in df.columns:
        df[ID_COLUMN] = df[ID_COLUMN].astype("string").str.strip()
    for col in (NAME_COLUMN, ADDRESS_COLUMN, COUNTRY_COLUMN):
        if col in df.columns:
            df[col] = df[col].astype("string")
    return df


def _read_csv(path: Path, nrows: int | None, usecols, chunksize: int | None):
    kwargs: dict = {
        "sep": "\t",
        "dtype": str,
        "keep_default_na": False,
        "na_values": list(NA_VALUES),
        "encoding": "utf-8",
    }
    if nrows is not None:
        kwargs["nrows"] = nrows
    if usecols is not None:
        kwargs["usecols"] = list(usecols)
    if chunksize is not None:
        kwargs["chunksize"] = chunksize
    return pd.read_csv(path, **kwargs)


def _header(path: Path) -> list[str]:
    with path.open("r", encoding="utf-8") as fh:
        return fh.readline().rstrip("\n").split("\t")


def find_file(directory: str | Path, *patterns: str) -> Path:
    """Locate a file inside ``directory`` by trying a set of name patterns.

    Falls back to a fuzzy search (``*source1*.tsv``) so the loader keeps working
    when the challenge files use slightly different prefixes.
    """
    directory = Path(directory)
    if not directory.is_dir():
        raise FileNotFoundError(f"Directory not found: {directory}")
    for pattern in patterns:
        candidate = directory / pattern
        if candidate.exists():
            return candidate
    for pattern in patterns:
        matches = sorted(directory.glob("*" + pattern))
        if matches:
            return matches[0]
    raise FileNotFoundError(
        f"None of {list(patterns)} found in {directory}. Available: "
        f"{[p.name for p in sorted(directory.glob('*'))]}"
    )


def read_tsv(
    path: str | Path,
    name: str | None = None,
    *,
    nrows: int | None = None,
    usecols: list[str] | None = None,
) -> pd.DataFrame:
    """Read a whole TSV into memory, coercing every column to ``str``.

    Warns when the file is large: the real Source 2/3 tables need several GB
    and should be streamed with :func:`read_tsv_chunks` instead.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"Required file not found: {path}\n"
            "Expected layout:\n"
            "  <root>/train/{train_source1,train_source2,train_source3,train_ground_truth}.tsv\n"
            "  <root>/test/{test_source1,test_source2,test_source3}.tsv"
        )
    label = name or path.name
    if nrows is None and path.stat().st_size > 200 * 1024**2:
        LOGGER.warning(
            "%s is %.0f MB; reading it whole may exhaust memory. "
            "Prefer read_tsv_chunks()/RawDataset.iter_chunks().",
            label, path.stat().st_size / 1024**2,
        )
    df = _normalise_columns(_read_csv(path, nrows, usecols, None))
    LOGGER.info("Loaded %-28s rows=%-10d cols=%s", label, len(df), list(df.columns))
    return df


def read_tsv_chunks(
    path: str | Path,
    chunksize: int = DEFAULT_CHUNK_ROWS,
    *,
    usecols: list[str] | None = None,
) -> Iterator[pd.DataFrame]:
    """Stream a TSV in fixed-size chunks with bounded memory."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    LOGGER.info("Streaming %-24s chunksize=%d cols=%s", path.name, chunksize, usecols or "all")
    for chunk in _read_csv(path, None, usecols, chunksize):
        yield _normalise_columns(chunk)


def source_path(split: str, source: str, root: str | Path | None = None) -> Path:
    """Path of ``<split>_<source>.tsv`` under ``root`` (auto-detected if ``None``)."""
    base = Path(root) if root is not None else dataset_root()
    directory = base if base.name == split else base / split
    return find_file(
        directory,
        f"{split}_{source}.tsv",
        f"{source}.tsv",
        f"{split}{source}.tsv",
    )


@dataclass
class RawDataset:
    """The three record tables for a split, already string-typed."""

    source1: pd.DataFrame
    source2: pd.DataFrame
    source3: pd.DataFrame
    split: str

    def table(self, source: str) -> pd.DataFrame:
        return {SOURCE1: self.source1, SOURCE2: self.source2, SOURCE3: self.source3}[source]

    def __iter__(self):
        for source in SOURCES:
            yield source, self.table(source)

    def iter_chunks(
        self,
        source: str,
        chunksize: int = DEFAULT_CHUNK_ROWS,
        *,
        usecols: list[str] | None = None,
        root: str | Path | None = None,
    ) -> Iterator[pd.DataFrame]:
        """Stream one source table of this split without materialising it."""
        yield from read_tsv_chunks(source_path(self.split, source, root), chunksize, usecols=usecols)

    @property
    def pool(self) -> pd.DataFrame:
        """Source 2 stacked on Source 3 -- the retrieval pool."""
        return pd.concat([self.source2, self.source3], ignore_index=True)


def load_split(root: str | Path | None = None, split: str = "train") -> RawDataset:
    """Load the three record tables for ``split`` into memory.

    ``root`` defaults to the auto-detected dataset root.  For the real data use
    :func:`stream_split` / :meth:`RawDataset.iter_chunks` instead of this.
    """
    tables = {}
    for source in SOURCES:
        path = source_path(split, source, root)
        tables[source] = read_tsv(path, name=f"{split}/{path.name}")
    return RawDataset(split=split, **tables)


def stream_split(split: str = "train", root: str | Path | None = None) -> dict[str, Path]:
    """Return the three file paths of a split without reading anything."""
    return {source: source_path(split, source, root) for source in SOURCES}


def load_train(train_dir: str | Path | None = None) -> RawDataset:
    """Load the training split."""
    return load_split(train_dir, "train")


def load_test(test_dir: str | Path | None = None) -> RawDataset:
    """Load the test split."""
    return load_split(test_dir, "test")


# --------------------------------------------------------------------------
# profiling
# --------------------------------------------------------------------------
def _text_len(series: pd.Series) -> np.ndarray:
    s = series.fillna("")
    return s.str.len().to_numpy(dtype="int32")


def _len_stats(parts: list[np.ndarray]) -> dict[str, object]:
    a = np.concatenate(parts) if parts else np.zeros(1, dtype="int32")
    return {
        "min": int(a.min()),
        "p25": int(np.percentile(a, 25)),
        "median": int(np.percentile(a, 50)),
        "mean": round(float(a.mean()), 2),
        "p75": int(np.percentile(a, 75)),
        "p95": int(np.percentile(a, 95)),
        "p99": int(np.percentile(a, 99)),
        "max": int(a.max()),
    }


def describe_dataframe(df: pd.DataFrame, label: str) -> dict[str, object]:
    """Collect shape / dtype / null / duplicate statistics for one in-memory table."""
    stats: dict[str, object] = {
        "label": label,
        "shape": tuple(int(x) for x in df.shape),
        "columns": list(df.columns),
        "dtypes": {c: str(t) for c, t in df.dtypes.items()},
        "null_counts": {c: int(df[c].isna().sum()) for c in df.columns},
        "null_fraction": {
            c: (float(df[c].isna().mean()) if len(df) else 0.0) for c in df.columns
        },
    }
    if ID_COLUMN in df.columns:
        ids = df[ID_COLUMN]
        stats["id_nulls"] = int(ids.isna().sum())
        stats["id_duplicates"] = int(ids.duplicated(keep=False).sum())
        stats["id_unique"] = int(ids.nunique(dropna=True))
    for col in (NAME_COLUMN, ADDRESS_COLUMN, COUNTRY_COLUMN):
        if col in df.columns:
            s = df[col].dropna().astype(str)
            stats[f"{col}_empty_string"] = int((s.str.strip() == "").sum())
            stats[f"{col}_unique"] = int(s.nunique())
            if len(s):
                stats[f"{col}_len_mean"] = round(float(s.str.len().mean()), 2)
                stats[f"{col}_len_median"] = float(s.str.len().median())
    for col in (NAME_COLUMN, ADDRESS_COLUMN):
        if col in df.columns and ID_COLUMN in df.columns:
            stats[f"{col}_duplicate_rows"] = int(df.duplicated(subset=[ID_COLUMN, col], keep=False).sum())
    return stats


def profile_tsv(
    path: str | Path,
    label: str | None = None,
    *,
    chunksize: int = DEFAULT_CHUNK_ROWS,
) -> dict[str, object]:
    """Stream a TSV and return the same statistics as :func:`describe_dataframe`.

    Bounded memory regardless of file size: ids and names are reduced to 64-bit
    hashes for the uniqueness counts, and length statistics are accumulated as
    int32 arrays.  The dataset is never modified.
    """
    path = Path(path)
    name = label or path.name
    cols = _header(path)

    rows = 0
    nulls = {c: 0 for c in cols}
    blank = {c: 0 for c in cols}
    countries: dict[str, int] = {}
    name_len: list[np.ndarray] = []
    addr_len: list[np.ndarray] = []
    id_hash: list[np.ndarray] = []
    name_hash: list[np.ndarray] = []
    id_bad_format = 0
    id_prefix: dict[str, int] = {}

    has_id = ID_COLUMN in cols
    has_name = NAME_COLUMN in cols
    has_addr = ADDRESS_COLUMN in cols
    has_country = COUNTRY_COLUMN in cols

    for chunk in read_tsv_chunks(path, chunksize, usecols=cols):
        rows += len(chunk)
        for c in nulls:
            s = chunk[c]
            nulls[c] += int(s.isna().sum())
            blank[c] += int((s.fillna("").str.strip() == "").sum())
        if has_country:
            for k, v in chunk[COUNTRY_COLUMN].fillna("<NA>").value_counts().to_dict().items():
                countries[str(k)] = countries.get(str(k), 0) + int(v)
        if has_name:
            name_len.append(_text_len(chunk[NAME_COLUMN]))
            name_hash.append(pd.util.hash_pandas_object(
                chunk[NAME_COLUMN].fillna(""), index=False).to_numpy(dtype="uint64"))
        if has_addr:
            addr_len.append(_text_len(chunk[ADDRESS_COLUMN]))
        if has_id:
            ids = chunk[ID_COLUMN].astype(str)
            id_hash.append(pd.util.hash_pandas_object(ids, index=False).to_numpy(dtype="uint64"))
            for pfx, cnt in ids.str.extract(r"^(S[123])-", expand=False).fillna("?").value_counts().items():
                id_prefix[str(pfx)] = id_prefix.get(str(pfx), 0) + int(cnt)
            id_bad_format += int((~ids.str.match(r"^S[123]-\d+$")).sum())

    ih = np.concatenate(id_hash) if id_hash else np.zeros(0, dtype="uint64")
    uniq_id, cnt_id = np.unique(ih, return_counts=True)
    nh = np.concatenate(name_hash) if name_hash else np.zeros(0, dtype="uint64")

    stats: dict[str, object] = {
        "label": name,
        "path": str(path),
        "size_mb": round(path.stat().st_size / 1024**2, 1),
        "header": cols,
        "columns": cols,
        "shape": (rows, len(cols)),
        "n_rows": rows,
        "dtypes": {c: "string (read with dtype=str)" for c in cols},
        "is_record_table": bool(has_id and has_name),
        "null_counts": nulls,
        "null_fraction": {c: (round(v / rows, 6) if rows else 0.0) for c, v in nulls.items()},
        "empty_or_whitespace_only": blank,
    }
    if has_id:
        stats["id_unique"] = int(uniq_id.size)
        stats["id_duplicates"] = int(cnt_id[cnt_id > 1].sum()) if cnt_id.size else 0
        stats["id_prefix_counts"] = id_prefix
        stats["id_bad_format"] = id_bad_format
    if nh.size:
        stats[f"{NAME_COLUMN}_unique"] = int(np.unique(nh).size)
    if name_len:
        stats[f"{NAME_COLUMN}_len"] = _len_stats(name_len)
    if addr_len:
        stats[f"{ADDRESS_COLUMN}_len"] = _len_stats(addr_len)
    if countries:
        stats["n_countries"] = len(countries)
        stats["country_counts"] = dict(sorted(countries.items(), key=lambda kv: -kv[1]))
    return stats
